### PR TITLE
Fixed errors caused by porting from windows -> linux + Ported Eigen to glm

### LINKED ISSUE #3: Port math logic from Eigen to GLM
GLM makes more sense due to 2/3 knowing it versus Eigen and it matching the syntax of GLSL math

### PR DESCRIPTION
**Pull request by rgarmsen2295**
Still have to switch from eigen to glm but am trying to be code review friendly by splitting stuff up a bit :)

Also, plenty of warnings, going for minimum build here first

Edit: Ugh, forgot to make a new branch, so the Eigen changes got pulled into here too...click on the commits to see the separate changes though if that helps!

Fixes #3

### CODE REVIEW

**Review by nurgan — APPROVED** [review]

**Review by nurgan — APPROVED** [review]

**Review by nurgan — APPROVED** [review]

File: src/BoundingBox.h [hunk 1]
```diff
@@ -1,8 +1,10 @@
 #ifndef BOUNDING_BOX_H
 #define BOUNDING_BOX_H
 
-#define EIGEN_DONT_ALIGN_STATICALLY
-#include <Eigen/Dense>
+#include "glm/glm.hpp"
+#include "glm/vec4.hpp"
```
Comment (joncatanio) [inline src/BoundingBox.h:5]: Is `vec3` included in `glm/vec4.hpp`? I haven't seen this header, we sure it's necessary?

File: src/GameObject.cpp [hunk 2]
```diff
@@ -47,52 +47,61 @@ GameObject::~GameObject() {
...
 
 	yRotationAngle_ = angle;
 	transform.setRotate(angle, yAxis);
 }
 
 void GameObject::calculateAndSetInitialRotation() {
 	if (velocity > 0.0f) {
-		float cosOfDir = Eigen::Vector3f(1.0f, 0.0f, 0.0f).dot(direction);
+		float cosOfDir = glm::dot(glm::vec3(-1.0f, 0.0f, 0.0f), direction);
+		float rotationAngle = (glm::acos(cosOfDir) * 180.0f / M_PI);
```
Comment (joncatanio) [inline src/GameObject.cpp:82]: In `MatrixStack::rotate` it looks like it expects the float in radians and does the conversion to degrees. This might be the spot of your problem with initial rotations? Also it looks like you need to divide `cosOfDir` by both the magnitude of the original orientation vector and the direction. Maybe it's not necessary, but just another idea.

**Review by joncatanio — APPROVED** [review]
Looks good, I'm gonna go ahead and merge this so Alex and I can get the code goin for us. Check out the few comments I made, I think I know what's up with the initial rotation problem.

File: src/BoundingBox.h (hunk 1 above)
Comment (rgarmsen2295) [reply src/BoundingBox.h:5]: Honestly, not sure, copy-pasted from another file as part of getting it working.  But it's probably not necessary if you don't think it is, I'll probably do a cleanup pass on stuff like that later today

File: src/GameObject.cpp (hunk 2 above)
Comment (rgarmsen2295) [reply src/GameObject.cpp:82]: It does? ugh, when I googled it sounded like it was in degrees, but that would make sense.

Both the direction and original vector (now the -xAxis) should already be normalized so I don't think that should be an issue but it's worth a shot!

Comment (joncatanio) [reply src/GameObject.cpp:82]: It's Zoe's doing I think haha, check out `MatrixStack::rotate` you'll see what I'm talkin' about. Also if they are already normalized then perf, don't worry about that then.
